resources:
  - backend.yaml
  - ingress.yaml
configMapGenerator:
  - name: java-backend-config
    files:
      - config.json=config/configback.json

generatorOptions:
  disableNameSuffixHash: true